Synesthesias/PLATEAU-SDK-for-Unreal

Source/PLATEAUEditor/Private/ExtentEditor/PLATEAUExtentEditorVPClient.cpp, Source/PLATEAUEditor/Private/ExtentEditor/PLATEAUExtentGizmo.cpp
範囲選択画面でのハンドルの追加に対応しました。
範囲選択画面にて、選択範囲の中央に位置するハンドルを操作すると選択範囲がそのままスライド移動します。
=> 範囲選択画面でのハンドル追加に対応

Source/PLATEAUEditor/Private/PLATEAUWindow.cpp
=> SDK画面のドッキング

LICENSE.md, Source/PLATEAUEditor/Private/ExtentEditor/PLATEAUFeatureInfoDisplay.cpp, Source/PLATEAUEditor/Private/ExtentEditor/PLATEAUFeatureInfoDisplay.h, Source/PLATEAUEditor/Private/PLATEAUBasemap.cpp, Source/PLATEAUEditor/Private/PLATEAUBasemap.h, Source/PLATEAUEditor/Private/SPLATEAUImportPanel.cpp, Source/PLATEAUEditor/Private/SPLATEAUImportPanel.h, Source/PLATEAURuntime/Private/PLATEAUCityModelLoader.cpp, Source/PLATEAURuntime/Public/PLATEAUGeometry.h
=> オフセット値の設定画面の追加

Source/PLATEAUEditor/Private/PLATEAUBasemap.cpp
=> Tile Map Load Error : FIle size check. Log表示

Source/PLATEAUEditor/Private/SPLATEAUImportPanel.cpp, Source/PLATEAUEditor/Private/SPLATEAUImportPanel.h, Source/PLATEAURuntime/Private/PLATEAUCityModelLoader.cpp, Source/PLATEAURuntime/Private/PLATEAUMeshLoader.cpp, Source/PLATEAURuntime/Public/PLATEAUCityModelLoader.h, Source/PLATEAURuntime/Public/PLATEAUMeshLoader.h
City Model Import キャンセル機能　
実装途中
=> City Model Import Cancellation.

Documentation/manual/ImportCityModels.md
=> Import Cancel機能のdocument追加

Source/PLATEAURuntime/Private/PLATEAUMeshExporter.cpp, Source/PLATEAURuntime/Private/PLATEAUMeshLoader.cpp, Source/PLATEAURuntime/Private/PLATEAUTextureLoader.cpp, Source/PLATEAURuntime/Public/PLATEAUMeshLoader.h
- バグ修正: Macでのインポートバグ、Mac&Winでエクスポートするモデルの乱れ 
- インポートでLODが正しく反映されない問題を修正
=> リリース準備 v1.0.3

Source/ThirdParty/include/plateau/dataset/city_model_package.h, Source/ThirdParty/lib/linux/libplateau.a, Source/ThirdParty/lib/macos/libplateau.a, Source/ThirdParty/lib/macos/libplateau_combined.a, Source/ThirdParty/lib/windows/plateau_combined.lib
libplateau Feature/lod4 import for building 2
libcitygml Feature/capable of importing lod4 buildings
=> LOD4 Import 用 library update

Source/PLATEAURuntime/Private/PLATEAUMeshLoader.cpp
CreateMeshDescriptionをGameThreadで実行するように変更
=> インポート時クラッシュ修正(CreateMeshDescription)

Source/PLATEAURuntime/Private/PLATEAUMeshExporter.cpp, Source/PLATEAURuntime/Private/PLATEAUTextureLoader.cpp
SDKでインポートされたテクスチャのアセット名に`.`が含まれているせいで破損しているとみなされていたため修正
=> テクスチャアセット名変更、ファイルパスをAssetImportDataに移行

Source/PLATEAURuntime/Private/PLATEAUMeshExporter.cpp, Source/PLATEAURuntime/Private/PLATEAUMeshLoader.cpp, Source/PLATEAURuntime/Private/PLATEAUTextureLoader.cpp
This reverts commit ca8e031e0d15c52aa8859a937f8326f1264390e3.
=> v1.3.1リリース候補(2)

Source/PLATEAUEditor/PLATEAUEditor.Build.cs, Source/PLATEAUEditorBPLibraries/PLATEAUEditorBPLibraries.Build.cs, Source/PLATEAURuntime/PLATEAURuntime.Build.cs, Source/PLATEAURuntime/Private/PLATEAUCityModelLoader.cpp, Source/PLATEAURuntime/Private/PLATEAUDllLoggerUnreal.h, Source/PLATEAURuntime/Public/PLATEAUDllLoggerUnreal.cpp, Source/PLATEAUTests/PLATEAUTests.Build.cs
=> インポート時の共通ライブラリ側の警告・エラーログがUnrealEngineで表示されるようにしました。

Documentation/manual/AccessCityObject.md
=> ドキュメント更新： 属性情報の取得機能で必要な設定

Source/PLATEAUEditorBPLibraries/Private/PLATEAUModelAdjustmentFilter.cpp, Source/PLATEAURuntime/Private/PLATEAUInstancedCityModel.cpp
・フィルタリング時に一度全メッシュを非表示にする対応が消えていた
=> モデル調整機能が動作しない不具合対応

Source/PLATEAUEditor/Private/ExtentEditor/PLATEAUAsyncLoadedFeatureInfoPanel.cpp, Source/PLATEAUEditor/Private/ExtentEditor/PLATEAUAsyncLoadedFeatureInfoPanel.h, Source/PLATEAUEditor/Private/PLATEAUBasemap.cpp, Source/PLATEAUEditorBPLibraries/Private/PLATEAUImportAreaSelectBtn.cpp, Source/PLATEAURuntime/Private/PLATEAUCityModelLoader.cpp
=> Macでのビルドエラー対応

Source/PLATEAURuntime/Private/PLATEAUMeshLoader.cpp
=> モデルエクスポートでクラッシュする不具合対応

Source/PLATEAURuntime/Private/PLATEAUMeshLoader.cpp
=> submesh / polygrp check を Log Errorに変更

Documentation/manual/Installation.md, Documentation/resources/manual/installation/addCppCodes.png, Documentation/resources/manual/installation/buildCodes.png, Documentation/resources/manual/installation/includeDialog.png, Documentation/resources/manual/installation/moduleError.png, Documentation/resources/manual/installation/newClass.png, Documentation/resources/manual/installation/openCodes.png, Documentation/resources/manual/installation/parentClass.png, Documentation/resources/manual/installation/unrealEngineNewProjectCategory.png
=> インストール項目のマニュアル更新

Source/PLATEAURuntime/Private/PLATEAUMeshLoader.cpp, Source/PLATEAURuntime/Private/PLATEAUTextureLoader.cpp, Source/PLATEAURuntime/Public/PLATEAUCityObjectGroup.h, Source/PLATEAURuntime/Public/PLATEAUImportSettings.h, Source/PLATEAURuntime/Public/PLATEAUMeshLoader.h, Source/PLATEAURuntimeBPLibraries/Private/Export/PLATEAUExportModelAPI.cpp, Source/PLATEAURuntimeBPLibraries/Private/Import/PLATEAUImportModelRuntimeAPI.cpp
=> マーケットプレイス出品用ビルドを通すための修正

Content/EUW/MainWindow.uasset
SDKアンケートページへの導線ボタンをメインページに追加。
SDKウィンドウを表示。
=> SDKアンケートページへの導線ボタン追加

Content/EUW/MainWindow.uasset
・「SDK利用者アンケート実施中」という表記に変更
・ボタン背景色を他と合わせる対応
PLATEAU SDKを開いてウィンドウ下部のアンケートボタンを確認する。
=> アンケートボタン改善対応

README.md
=> アンケートリンクを修正しました

Content/EUW/RoadAdjsutmentGenerateTab.uasset
Reverts Synesthesias/PLATEAU-SDK-for-Unreal#249
=> Revert "道路調整→生成のマテリアル分けの生成結果を整理"

Source/PLATEAURuntime/Public/RoadNetwork/GeoGraph/GeoGraphEx.h
GeoGraphExでコンパイルエラーになる場合があったので修正
=> fix : GetEdgeSegmentでコンパイラによってエラーになるので修正

Source/PLATEAURuntime/Private/RoadNetwork/Structure/PLATEAURnModelDrawerDebug.cpp, Source/PLATEAURuntime/Private/RoadNetwork/Structure/RnLane.cpp, Source/PLATEAURuntime/Private/RoadNetwork/Structure/RnRoadGroup.cpp
車線の中央線の生成処理とそのデバッグ表示
道路構造を生成し, PIPでPLATEAURnStructureModelのDebug->LaneOption -> Show Center Way のVisible をtrueにしてみて、表示されるか確認
=> update : URnLaneのGetCenterWayの対応とデバッグ表示

Content/EUW/ModelReconstructSetTab.uasset
=> マテリアル分けのパッケージ選択時Actorがnullptrになる

Content/EUW/RoadAdjsutmentGenerateTab.uasset, Source/PLATEAURuntime/Private/PLATEAUInstancedCityModel.cpp, Source/PLATEAURuntime/Private/Reconstruct/PLATEAUMeshLoaderForClassification.cpp, Source/PLATEAURuntime/Private/Reconstruct/PLATEAUModelClassificationByAttribute.cpp, Source/PLATEAURuntime/Private/Reconstruct/PLATEAUModelClassificationByType.cpp, Source/PLATEAURuntime/Public/PLATEAUCachedMaterialArray.h, Source/PLATEAURuntime/Public/PLATEAUInstancedCityModel.h, Source/PLATEAURuntime/Public/Reconstruct/PLATEAUModelClassification.h, Source/PLATEAURuntime/Public/Reconstruct/PLATEAUModelClassificationByAttribute.h, Source/PLATEAURuntime/Public/Reconstruct/PLATEAUModelClassificationByType.h, Source/PLATEAURuntime/Public/Reconstruct/PLATEAUModelReconstruct.h, Source/PLATEAURuntimeBPLibraries/Private/ModelClassification/PLATEAUModelClassificationAPI.cpp, Source/PLATEAURuntimeBPLibraries/Public/ModelClassification/PLATEAUModelClassificationAPI.h
道路ネットワーク生成で、属性情報がない道路も車道マテリアルに変わる
=> 道路ネットワーク生成で、属性情報がない道路も車道マテリアルに変える

Content/RoadNetwork/Meshes/Common_White_01_MAT_012.uasset, Content/RoadNetwork/Meshes/Common_White_01_MAT_013.uasset, Content/RoadNetwork/Meshes/Common_White_01_MAT_014.uasset, Content/RoadNetwork/Meshes/Common_White_01_MAT_015.uasset, Content/RoadNetwork/Meshes/Common_White_01_MAT_016.uasset, Content/RoadNetwork/Meshes/RoadMarkArrowLeft.uasset, Content/RoadNetwork/Meshes/RoadMarkArrowRight.uasset, Content/RoadNetwork/Meshes/RoadMarkArrowStraight.uasset, Content/RoadNetwork/Meshes/RoadMarkArrowStraightLeft.uasset, Content/RoadNetwork/Meshes/RoadMarkArrowStraightRight.uasset, Source/PLATEAURuntime/Private/PLATEAUMeshExporter.cpp, Source/PLATEAURuntime/Private/RoadAdjust/PLATEAUReproducedRoad.cpp, Source/PLATEAURuntime/Private/RoadAdjust/RoadMarking/DirectionalArrowComposer.cs, Source/PLATEAURuntime/Private/RoadAdjust/RoadMarking/PLATEAUDirectionalArrowComposer.cpp, Source/PLATEAURuntime/Private/RoadNetwork/Structure/RnIntersection.cpp, Source/PLATEAURuntime/Private/RoadNetwork/Structure/RnWay.cpp, Source/PLATEAURuntime/Public/PLATEAUMeshExporter.h, Source/PLATEAURuntime/Public/RoadAdjust/RoadMarking/PLATEAUDirectionalArrowComposer.h, Source/PLATEAURuntime/Public/RoadNetwork/Structure/RnIntersection.h
- 道路ネットワーク生成で交差点前の矢印が表示されるようにしました
=> 交差点前の矢印生成機能をUnityから移植

Content/EUW/RoadAdjsutmentGenerateTab.uasset
=> 道路ネットワーク生成時にボタン非活性化
